/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "clip-monorepo"


// Enable the feature to manage versions in one place
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

// Register your KMP/CMP project modules
include(":apps:Clip:composeApp")
//include(":apps:Clip:shared")
