/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        google()            // <--- Esta es la que falta y es CRITICA para AGP
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "clip-monorepo"




// Enable the feature to manage versions in one place
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}


// Register your KMP/CMP project modules
include(":composeApp")
//include(":apps:Clip:shared")

//project(":composeApp").projectDir = file("apps/Clip/composeApp")
//project(":composeApp").projectDir = File(rootDir, "apps/Clip/composeApp")
//project(":composeApp").projectDir = rootProject.file("apps/Clip/composeApp")
//project(":composeApp").projectDir = File(rootDir, "apps/Clip/composeApp")
project(":composeApp").projectDir = File(settingsDir, "apps/Clip/composeApp")
//project(":apps:Clip:shared").projectDir = file("apps/Clip/shared")